pageinfo = [[1179678471,12231],
	[1179678557,11219],
	[1180208905,24887],
	[1180361619,12559],
	[1180925373,5624],
	[1182129301,11310],
	[1198803563,19141],
	[1198803573,32459],
	[1198803583,28844],
	[1210595869,10299],
	[1210597765,12091],
	[1213127949,7671],
	[1179623747,1863],
	[1181592647,5968],
	[1181650869,3415],
	[1181627407,11834],
	[1181626795,3469],
	[1181626911,2552],
	[1213128855,3778],
	[1179846053,536],
	[1181651273,2369],
	[1190779857,3321],
	[1190782291,5409],
	[1190781245,2629],
	[1190781571,2845],
	[1190781285,2692],
	[1190781343,2733],
	[1190781521,2885],
	[1190779997,2396],
	[1190780155,2611],
	[1190955995,3279],
	[1190641169,7474],
	[1197771731,3274],
	[1197771735,5666],
	[1197771745,2573],
	[1190645575,2404],
	[1190645579,2525],
	[1190645583,7056],
	[1197771755,4049],
	[1190645587,3883],
	[1190645593,2366],
	[1190645595,2358],
	[1197771761,4120],
	[1197771765,4166],
	[1198800183,6178],
	[1197771771,4204],
	[1197771795,3879],
	[1190645609,2406],
	[1190645615,2416],
	[1197771799,4336],
	[1190645619,2385],
	[1190645625,2505],
	[1179699711,6607],
	[1210596383,2426],
	[1182130685,3395],
	[1182129509,2314],
	[1182129485,2568],
	[1190635055,3320],
	[1179714625,6558],
	[1197771863,7556],
	[1197771841,2476],
	[1190595691,2351],
	[1190595705,2409],
	[1197771853,3656],
	[1190596063,2403],
	[1190596155,2541],
	[1179714323,2381],
	[1197771817,2718],
	[1190591907,4603],
	[1190591589,3989],
	[1179714059,2300],
	[1198800931,2691],
	[1197771827,6192],
	[1198799923,2607],
	[1190592661,3938],
	[1197591537,8687],
	[1179673719,2386],
	[1179673727,2412],
	[1179677049,3117],
	[1190903603,2511],
	[1179674397,2326],
	[1179674453,2391],
	[1190903607,2545],
	[1179674679,2495],
	[1179675193,2327],
	[1190903611,2578],
	[1179676985,3141],
	[1179675459,2554],
	[1181625877,2569],
	[1190596353,2605],
	[1197714795,3290],
	[1179677277,2614],
	[1200410897,5277],
	[1200410883,5168],
	[1179677869,2940],
	[1197772629,4505],
	[1198796967,3985],
	[1198797039,4204],
	[1200480967,2352],
	[1190955253,2866],
	[1190955307,2777],
	[1210597477,8501],
	[1210597643,13408],
	[1190595023,2495],
	[1190595275,2526],
	[1190834475,2600],
	[1190834495,2589],
	[1190903595,2597],
	[1190903597,2527],
	[1190857319,2399],
	[1180280963,2385],
	[1180280971,2373],
	[1180280975,2367],
	[1180209207,2477],
	[1190812531,2393],
	[1181594955,2507],
	[1198797237,2952],
	[1198797233,2961],
	[1179678033,2493],
	[1200480873,2609],
	[1179838771,2067],
	[1185217557,2319],
	[1179676053,2533],
	[1179673963,2517],
	[1179673967,2890],
	[1179673971,2522],
	[1179675849,2884],
	[1190594651,2393],
	[1190595193,2376],
	[1190857263,2401],
	[1180280983,2386],
	[1180280989,2374],
	[1180280995,2372],
	[1179673825,3679],
	[1190783107,3732],
	[1197772301,3873],
	[1179673821,3716],
	[1190639819,3766],
	[1180210497,4013],
	[1197688077,3953],
	[1197688197,3759],
	[1197688221,3751],
	[1185217497,2483],
	[1190639803,3682],
	[1190639799,4082],
	[1190646811,3603],
	[1190639775,3723],
	[1190639785,3554],
	[1190639773,3599],
	[1179673883,3635],
	[1180280681,3651],
	[1180280747,3622],
	[1180280783,3623],
	[1179673887,3637],
	[1190547951,3809],
	[1190547891,4282],
	[1179673903,3736],
	[1179673909,4053],
	[1213128305,3740],
	[1197771677,4244],
	[1213128293,3757],
	[1190856251,3882],
	[1190547819,3567],
	[1190856213,5108],
	[1190855877,3751],
	[1198803077,3737],
	[1198803197,2623],
	[1179668113,3445],
	[1179668165,3424],
	[1179673923,3549],
	[1197771687,4298],
	[1179673931,3609],
	[1190551243,4282],
	[1197688243,3776],
	[1179673941,4227],
	[1213128183,3740],
	[1197771693,4244],
	[1213128275,3757],
	[1190551121,3493],
	[1190551305,4295],
	[1190551373,3504],
	[1198803085,3737],
	[1198803231,2623],
	[1179668121,3444],
	[1179668159,3423],
	[1179673953,3548],
	[1197771699,4375],
	[1190782831,3602],
	[1182130961,2306],
	[1182130823,3390],
	[1182130329,2322],
	[1182130337,2572],
	[1181660915,3137],
	[1182129413,2627],
	[1181660529,2416],
	[1181664259,3564],
	[1179718685,7536],
	[1185216625,3724],
	[1185216715,2463],
	[1181660289,3007],
	[1179717145,2589],
	[1179717157,2385],
	[1181652405,4771],
	[1179844355,2398],
	[1179844117,2321],
	[1190635139,3284],
	[1190635421,3230],
	[1181656477,2525],
	[1179699781,6441],
	[1179685633,1889],
	[1179685517,1896],
	[1179702163,2396],
	[1198798943,2993],
	[1179709629,2325],
	[1198799301,2683],
	[1198799363,2614],
	[1198799523,2651],
	[1198799521,2610],
	[1181664803,3334],
	[1179717597,2364],
	[1179717549,2382],
	[1179717575,2461],
	[1180361561,2498],
	[1179717787,2418],
	[1179717723,2455],
	[1180361555,2478],
	[1179717805,2489],
	[1181704553,2354],
	[1181704579,2387],
	[1181704621,2520],
	[1181704821,2483],
	[1181704777,2412],
	[1181704847,2440],
	[1181704929,2642],
	[1181704987,2479],
	[1181660123,3322],
	[1179710857,6518],
	[1197771909,3061],
	[1198800585,3079],
	[1210596459,3106],
	[1198800653,2360],
	[1198802029,2681],
	[1198802247,2589],
	[1197771901,3656],
	[1198802145,2563],
	[1197771895,2430],
	[1198800253,2499],
	[1198800171,6138],
	[1198801909,2978],
	[1198799971,2336],
	[1198800247,2493],
	[1181658799,2912],
	[1181658997,2398],
	[1181659097,2519],
	[1181659185,2357],
	[1181659199,2214],
	[1197771665,6316],
	[1197771655,4724],
	[1179719215,2324],
	[1197771669,6292],
	[1181652943,6857],
	[1179704595,3182],
	[1179704043,2587],
	[1179704233,2870],
	[1179699457,3179],
	[1179698699,2611],
	[1179698967,2709],
	[1179699099,2757],
	[1181673183,2487],
	[1179686791,2329],
	[1179686855,2396],
	[1185217115,2368],
	[1179699185,2551],
	[1197771721,2364],
	[1181680677,2448],
	[1179687345,2550],
	[1185214761,2422],
	[1185215145,2386],
	[1185214755,2405],
	[1181671093,2483],
	[1179686883,2393],
	[1185217083,2383],
	[1197771071,2903],
	[1197771707,2620],
	[1198798731,2569],
	[1200199453,2709],
	[1190645559,2546],
	[1185214775,2558],
	[1185215145,2317],
	[1185214767,2539],
	[1179715401,2776],
	[1179686031,2324],
	[1179684741,2748],
	[1179684751,2752],
	[1190551635,6107],
	[1190782601,5169],
	[1182129073,2299],
	[1182129153,2554],
	[1198797839,6013],
	[1198798121,2323],
	[1198798159,2572],
	[1181659997,3438],
	[1182130971,2557],
	[1179623759,1900],
	[1210597497,4838],
	[1181521009,12473],
	[1181520097,1926],
	[1181520069,1913],
	[1181520117,1912],
	[1181520015,1928],
	[1181520053,1913],
	[1181520037,1917],
	[1190992593,50036],
	[1181704037,11844],
	[1185217693,18295],
	[1181569679,11389],
	[1198802513,4666],
	[1197771573,2727],
	[1180264693,2077]];
pagedata = [ ["./changesinversion0_5_3beta.html","Changes in version 0.5.3 Beta","Top Previous Next Changes in version 0.5.3 Beta Additions • Added the ability to cancel point selection via onBeforeSelectPoint event handler • Ad...",""],
["./changesinversion0_6_0beta.html","Changes in version 0.6.0 Beta","Top Previous Next Changes in version 0.6.0 Beta Additions • Added setDataHandler to series in order to allow easy modification of the data handler...",""],
["./changesinversion0_7_1beta.html","Changes in version 0.7.1 Beta","Top Previous Next Changes in version 0.7.1 Beta Additions • Added trend series with support for linear trends • Added CSVFileDataHandler class • A...",""],
["./changesinversion0_8_0beta.html","Changes in version 0.8.0 Beta","Top Previous Next Changes in version 0.8.0 Beta Additions • Added chart.show_titlebar property and chart.showTitlebar()/chart.hideTitlebar() metho...",""],
["./changes_in_version_0_8_1_beta.html","Changes in version 0.8.1 Beta","Top Previous Next Changes in version 0.8.1 Beta Additions none in this release Modifications none in this release Bug Fixes • Fixed loading issues...",""],
["./changes_in_version_1_0.html","Changes in version 1.0","Top Previous Next Changes in version 1.0 Additions • Added an optional redraw flag into Chart.removeSeries in order to allow for multiple removes ...",""],
["./changes_in_version_1_0_1.html","Changes in version 1.0.1","Top Previous Next Changes in version 1.0.1 Additions • Added series.opacity property • Added series.setOpacity method • Added series.lineOpacity p...",""],
["./changes_in_version_1_1.html","Changes in version 1.1","Top Previous Next Changes in version 1.1 Additions • Added new series type AnalogGaugeSeries • Added onBeforeBeginZoom, onBeforeEndZoom and onAfte...",""],
["./changes_in_version_1_2.html","Changes in version 1.2","Top Previous Next Changes in version 1.2 Additions • Added classes to better control and track axis bins (text labels) • Added support for y axis ...",""],
["./changes_in_version_1_2_1.html","Changes in version 1.2.1","Top Previous Next Changes in version 1.2.1 Additions • Added selectPoint and clearSelectedPoint methods to the chart. Modifications • Enhanced sup...",""],
["./changes_in_version_1_3.html","Changes in version 1.3","Top Previous Next Changes in version 1.3 Additions • Added AreaSeries.closeLine property which determines if the line should return to the zero pl...",""],
["./changes_in_version_1_3_1.html","Changes in version 1.3.1","Top Previous Next Changes in version 1.3.1 Additions • Added Chart.y_axis_min_tick_interval, y_axis_max_tick_interval, x_axis_min_tick_interval an...",""],
["./customization.html","Customization","Top Previous Next Customization Enter topic text here. ",""],
["./dataformats.html","Data Formats","Top Previous Next Data Formats The following is a brief summary of the data formats supported by Emprise JavaScript Charts. For additional informa...",""],
["./dataformats_xmlcompact.html","XML - Compact","Top Previous Next XML - Compact The compact xml format is geared towards larger data sets which need to reduce the overhead associated with transf...",""],
["./dataformats_xmlfull.html","XML - Full","Top Previous Next XML - Full The full xml format is the most verbose and the most human readable of the supported formats. This format is ideal fo...",""],
["./dataformats_xmlshort.html","XML - Short","Top Previous Next XML - Short The short XML format provides the same functionality as the full format but with less transfer overhead (there is no...",""],
["./deployment.html","Deployment","Top Previous Next Deployment The Emprise JavaScript Charts distribution package includes a compressed and obfuscated version of the source code fo...",""],
["./ejschart_ftsearch.html","Emprise JavaScript Charts","Emprise JavaScript Charts Contents &#166; Index &#166; Search Enter one or more keywords to search (&#39;*&#39; and &#39;?&#39; wildcards are supported): You must have Java...",""],
["./EJSChart_headframe.html","Emprise JavaScript Charts Developer Guide","Emprise JavaScript Charts Developer Guide Content of the top frame goes here... ",""],
["./ejscnamespace.html","EJSC","Top Previous Next EJSC Properties Top level namespace for all classes and variables used by the Emprise JavaScript Charts package. Use of this nam...",""],
["./ejsc_ajaxdatahandler.html","EJSC.AjaxDataHandler","Top Previous Next EJSC.AjaxDataHandler Hierarchy Properties Methods Events Base data handler class for all Ajax data handlers (i.e. EJSC.XMLDataHa...",""],
["./ejsc_ajaxdatahandler_events_onneedsdata.html","onNeedsData (inherited)","Top Previous Next EJSC.AjaxDataHandler.onNeedsData See Also Definition boolean onNeedsData( EJSC.AjaxDataHandler dataHandler, EJSC.Series series, ...",""],
["./ejsc_ajaxdatahandler_methods_geturl.html","getUrl (inherited)","Top Previous Next EJSC.AjaxDataHandler.getUrl See Also Definition string getUrl( ) Description Returns the url string currently stored in the Ajax...",""],
["./ejsc_ajaxdatahandler_methods_setrequesttype.html","setRequestType (inherited)","Top Previous Next EJSC.AjaxDataHandler.setRequestType See Also Definition void setRequestType( string requestType, boolean reload ) Description Up...",""],
["./ejsc_ajaxdatahandler_methods_seturl.html","setUrl (inherited)","Top Previous Next EJSC.AjaxDataHandler.setUrl See Also Definition void setUrl( string url, boolean reload ) Description Updates the url string sto...",""],
["./ejsc_ajaxdatahandler_methods_seturldata.html","setUrlData (inherited)","Top Previous Next EJSC.AjaxDataHandler.setUrlData See Also Definition void setUrlData( string urlData, boolean reload ) Description Updates the ur...",""],
["./ejsc_ajaxdatahandler_methods_setxmldata.html","setXMLData (inherited)","Top Previous Next EJSC.AjaxDataHandler.setXMLData See Also Definition void setXMLData( XMLHttpRequest request ) Description This method allows pas...",""],
["./ejsc_ajaxdatahandler_properties_requesttype.html","requestType (inherited)","Top Previous Next EJSC.AjaxDataHandler.requestType See Also Definition string requestType = \"GET\" Description Defines the type of HTTP request to ...",""],
["./ejsc_ajaxdatahandler_properties_url.html","url (inherited)","Top Previous Next EJSC.AjaxDataHandler.url See Also Definition string url = null Description Defines the url currently being used to retrieve data...",""],
["./ejsc_ajaxdatahandler_properties_urldata.html","urlData (inherited)","Top Previous Next EJSC.AjaxDataHandler.urlData See Also Definition string urlData = null Description Defines the data to be included for both POST...",""],
["./ejsc_analoggaugeseries.html","EJSC.AnalogGaugeSeries","Top Previous Next EJSC.AnalogGaugeSeries Hierarchy Properties Methods Events In order to use the AnalogGaugeSeries, the file EJSChart_Gauges.js mu...",""],
["./ejsc_analoggaugeseries_properties_anchor.html","anchor","Top Previous Next EJSC.AnalogGaugeSeries.anchor See Also: Using Colors Definition object anchor = { color: &#39;rgb(0,0,0)&#39; , opacity: 100 , size: 10 ...",""],
["./ejsc_analoggaugeseries_properties_axis.html","axis","Top Previous Next EJSC.AnalogGaugeSeries.axis See Also: Using Colors Definition object axis = { color: &#39;rgb(255,255,255)&#39; , innerBorderColor: &#39;rgb...",""],
["./ejsc_analoggaugeseries_properties_fillcolor.html","fillColor","Top Previous Next EJSC.AnalogGaugeSeries.fillColor See Also: Using Colors Definition string fillColor = undefined Description Defines the backgrou...",""],
["./ejsc_analoggaugeseries_properties_fillopacity.html","fillOpacity","Top Previous Next EJSC.AnalogGaugeSeries.fillOpacity See Also Definition integer fillOpacity = 100 Description Defines the opacity for the backgro...",""],
["./ejsc_analoggaugeseries_properties_height.html","height","Top Previous Next EJSC.AnalogGaugeSeries.height See Also Definition string height = \"100%\" Description Defines the total height of the gauge. This...",""],
["./ejsc_analoggaugeseries_properties_label.html","label","Top Previous Next EJSC.AnalogGaugeSeries.label See Also Definition object label = { className: &#39;&#39; , textAlign: &#39;center&#39; , position: &#39;centerBottom&#39;...",""],
["./ejsc_analoggaugeseries_properties_lock.html","lock","Top Previous Next EJSC.AnalogGaugeSeries.lock See Also: Using Colors Definition object lock = { color: &#39;rgb(0,0,0)&#39; , offset: 5 , opacity: 100 , s...",""],
["./ejsc_analoggaugeseries_properties_marker_position.html","marker_position","Top Previous Next EJSC.AnalogGaugeSeries.marker_position See Also Definition string marker_position = \"outer\" Description Defines where the tick m...",""],
["./ejsc_analoggaugeseries_properties_max.html","max","Top Previous Next EJSC.AnalogGaugeSeries.max See Also Definition float max = 100 Description Defines the maximum value to be displayed on the gaug...",""],
["./ejsc_analoggaugeseries_properties_min.html","min","Top Previous Next EJSC.AnalogGaugeSeries.min See Also Definition float min = 0 Description Defines the minimum value to be displayed on the gauge. ",""],
["./ejsc_analoggaugeseries_properties_minortick.html","minorTick","Top Previous Next EJSC.AnalogGaugeSeries.minorTick See Also: Using Colors Definition object minorTick = { color: &#39;rgb(150,150,150)&#39; , count: 4 , o...",""],
["./ejsc_analoggaugeseries_properties_needle.html","needle","Top Previous Next EJSC.AnalogGaugeSeries.needle See Also: Using Colors Definition object needle = { borderColor: &#39;rgb(0,0,0)&#39; , borderOpacity: 100...",""],
["./ejsc_analoggaugeseries_properties_position.html","position","Top Previous Next EJSC.AnalogGaugeSeries.position See Also Definition string position = \"center\" Description Defines the quadrant of the chart tha...",""],
["./ejsc_analoggaugeseries_properties_range.html","range","Top Previous Next EJSC.AnalogGaugeSeries.range See Also: Using Colors Definition object range = { borderColor: &#39;rgb(0,0,0)&#39; , borderWidth: 1 , off...",""],
["./ejsc_analoggaugeseries_properties_ranges.html","ranges","Top Previous Next EJSC.AnalogGaugeSeries.ranges See Also: Using Colors Definition array ranges = new Array(); Description Defines a series of rang...",""],
["./ejsc_analoggaugeseries_properties_range_degrees.html","range_degrees","Top Previous Next EJSC.AnalogGaugeSeries.range_degrees See Also Definition integer range_degrees = 180 Description Defines the total angle (in deg...",""],
["./ejsc_analoggaugeseries_properties_start_degree.html","start_degree","Top Previous Next EJSC.AnalogGaugeSeries.start_degree See Also Definition integer start_degree = 270 Description Defines the angle (in degrees) at...",""],
["./ejsc_analoggaugeseries_properties_tick.html","tick","Top Previous Next EJSC.AnalogGaugeSeries.tick See Also: Using Colors Definition object tick = { className: &#39;&#39; , color: &#39;rgb(0,0,0)&#39; , offset: 0 , ...",""],
["./ejsc_analoggaugeseries_properties_tickcount.html","tickCount","Top Previous Next EJSC.AnalogGaugeSeries.tickCount See Also Definition integer tickCount = 11 Description Defines the number of major ticks to be ...",""],
["./ejsc_analoggaugeseries_properties_width.html","width","Top Previous Next EJSC.AnalogGaugeSeries.width See Also Definition string width = \"100%\" Description Defines the total width of the gauge. This ma...",""],
["./ejsc_areaseries.html","EJSC.AreaSeries","Top Previous Next EJSC.AreaSeries Hierarchy Properties Methods Events AreaSeries is rendered by drawing a line from point to point and then fillin...",""],
["./ejsc_areaseries_properties_closeline.html","closeLine","Top Previous Next EJSC.AreaSeries.closeLine See Also Definition boolean closeLine = true Description Defines whether the line drawn around the are...",""],
["./ejsc_arraydatahandler.html","EJSC.ArrayDataHandler","Top Previous Next EJSC.ArrayDataHandler Hierarchy Methods Events ArrayDataHandler converts the JavaScript array of points into a format that the S...",""],
["./ejsc_arraydatahandler_methods_getarray.html","getArray","Top Previous Next EJSC.ArrayDataHandler.getArray See Also Definition array getArray( ) Description Returns the data array currently stored in the ...",""],
["./ejsc_arraydatahandler_methods_setarray.html","setArray","Top Previous Next EJSC.ArrayDataHandler.setArray See Also Definition void setArray( array data ) Description Updates the data array stored in the ...",""],
["./ejsc_barpoint.html","EJSC.BarPoint","Top Previous Next EJSC.BarPoint Hierarchy Properties BarPoint is used to store an X,Y point value (and optionally user defined data). This is used...",""],
["./ejsc_barseries.html","EJSC.BarSeries","Top Previous Next EJSC.BarSeries Hierarchy Properties Methods Events BarSeries renders its points as vertical bars. The constructor expects an ins...",""],
["./ejsc_barseries_events_onbarneedscolor.html","onBarNeedsColor","Top Previous Next EJSC.Series.onBarNeedsColor See Also: Using Colors Definition string onBarNeedsColor( EJSC.BarPoint point, EJSC.Series series, E...",""],
["./ejsc_barseries_methods_addrange.html","addRange","Top Previous Next EJSC.BarSeries.addRange See Also: Using Colors Definition void addRange( float min, float max, string color, integer opacity, in...",""],
["./ejsc_barseries_methods_clearranges.html","clearRanges","Top Previous Next EJSC.BarSeries.clearRanges See Also Definition void clearRanges( boolean redraw ) Description Clears all ranges defined for the ...",""],
["./ejsc_barseries_methods_deleterange.html","deleteRange","Top Previous Next EJSC.BarSeries.deleteRange See Also Definition void deleteRange( float min, float max, boolean redraw ) Description Deletes the ...",""],
["./ejsc_barseries_methods_setdefaultcolors.html","setDefaultColors","Top Previous Next EJSC.BarSeries.setDefaultColors See Also: Using Colors Definition void setDefaultColors( array colors, boolean reload ) Descript...",""],
["./ejsc_barseries_methods_setgroupedbars.html","setGroupedBars","Top Previous Next EJSC.BarSeries.setGroupedBars See Also Definition void setGroupedBars( boolean grouped, boolean redraw ) Description Changes the...",""],
["./ejsc_barseries_methods_setintervaloffset.html","setIntervalOffset","Top Previous Next EJSC.BarSeries.setIntervalOffset See Also Definition void setIntervalOffset( float offset, boolean redraw ) Description Updates ...",""],
["./ejsc_barseries_methods_setlinewidth.html","setLineWidth","Top Previous Next EJSC.BarSeries.setLineWidth See Also Definition void setLineWidth( integer width ) Description Updates the lineWidth property an...",""],
["./ejsc_barseries_properties_defaultcolors.html","defaultColors","Top Previous Next EJSC.BarSeries.defaultColors See Also: Using Colors Definition array defaultColors = EJSC.DefaultBarColors Description Defines t...",""],
["./ejsc_barseries_properties_groupedbars.html","groupedBars","Top Previous Next EJSC.BarSeries.groupedBars See Also Definition boolean groupedBars = true Description Defines whether the bars from different ba...",""],
["./ejsc_barseries_properties_intervaloffset.html","intervalOffset","Top Previous Next EJSC.BarSeries.intervalOffset See Also Definition float intervalOffset = 0.8 Description Defines the spacing between the bars as...",""],
["./ejsc_barseries_properties_linewidth.html","lineWidth","Top Previous Next EJSC.BarSeries.lineWidth See Also Definition integer lineWidth = 1 Description Defines the width of the border around bars. ",""],
["./ejsc_barseries_properties_orientation.html","orientation","Top Previous Next EJSC.BarSeries.orientation See Also Definition string orientation = \"vertical\" Description This property determines the orientat...",""],
["./ejsc_barseries_properties_ranges.html","ranges","Top Previous Next EJSC.BarSeries.ranges See Also: Using Colors Definition array ranges = new Array() Description This property is used to store th...",""],
["./ejsc_barseries_properties_treelegend.html","treeLegend","Top Previous Next EJSC.BarSeries.treeLegend See Also Definition boolean treeLegend = false Description Defines whether to display each bar individ...",""],
["./ejsc_barseries_properties_usecolorarray.html","useColorArray","Top Previous Next EJSC.BarSeries.useColorArray See Also Definition boolean useColorArray = false Description Defines whether to make use of the EJ...",""],
["./ejsc_chart.html","EJSC.Chart","Top Previous Next EJSC.Chart Hierarchy Properties Methods Events Chart class that holds all the generic information for each chart that is being c...",""],
["./ejsc_chart_events_onafterdraw.html","onAfterDraw","Top Previous Next EJSC.Chart.onAfterDraw See Also Definition void onAfterDraw( EJSC.Chart chart ) Description Called after a drawing option has co...",""],
["./ejsc_chart_events_onaftermove.html","onAfterMove","Top Previous Next EJSC.Chart.onAfterMove See Also Definition void onAfterMove( EJSC.Chart chart ) Description Called after the chart has been drag...",""],
["./ejsc_chart_events_onafterselectpoint.html","onAfterSelectPoint","Top Previous Next EJSC.Chart.onAfterSelectPoint See Also Definition void onAfterSelectPoint( EJSC.Point point, EJSC.Series series, EJSC.Chart char...",""],
["./ejsc_chart_events_onaftershowcrosshairs.html","onAfterShowCrosshairs","Top Previous Next EJSC.Chart.onAfterShowCrosshairs See Also Definition void onAfterShowCrosshairs( float x, float y, EJSC.Chart chart ) Descriptio...",""],
["./ejsc_chart_events_onafterunselectpoint.html","onAfterUnselectPoint","Top Previous Next EJSC.Chart.onAfterUnselectPoint See Also Definition void onAfterUnselectPoint( ) Description Called after a point has lost selec...",""],
["./ejsc_chart_events_onafterzoom.html","onAfterZoom","Top Previous Next EJSC.Chart.onAfterZoom See Also Definition void onAfterZoom( EJSC.Chart chart ) Description Called after the chart has been zoom...",""],
["./ejsc_chart_events_onbeforebeginzoom.html","onBeforeBeginZoom","Top Previous Next EJSC.Chart.onBeforeBeginZoom See Also Definition boolean onBeforeBeginZoom( EJSC.Chart chart, float x, float y ) Description Cal...",""],
["./ejsc_chart_events_onbeforedblclick.html","onBeforeDblClick","Top Previous Next EJSC.Chart.onBeforeDblClick See Also Definition boolean onBeforeDblClick( EJSC.Chart chart ) Description Called before the chart...",""],
["./ejsc_chart_events_onbeforedraw.html","onBeforeDraw","Top Previous Next EJSC.Chart.onBeforeDraw See Also Definition boolean onBeforeDraw( ) Description Called before the chart is drawn. If return is f...",""],
["./ejsc_chart_events_onbeforeendzoom.html","onBeforeEndZoom","Top Previous Next EJSC.Chart.onBeforeEndZoom See Also Definition boolean onBeforeEndZoom( EJSC.Chart chart, float x, float y ) Description Called ...",""],
["./ejsc_chart_events_onbeforeselectpoint.html","onBeforeSelectPoint","Top Previous Next EJSC.Chart.onBeforeSelectPoint See Also Definition boolean onBeforeSelectPoint( EJSC.Point point, EJSC.Series series, EJSC.Chart...",""],
["./ejsc_chart_events_onbeforeunselectpoint.html","onBeforeUnselectPoint","Top Previous Next EJSC.Chart.onBeforeUnselectPoint See Also Definition void onBeforeUnselectPoint( EJSC.Point point ) Description Called before a ...",""],
["./ejsc_chart_events_ondblclickpoint.html","onDblClickPoint","Top Previous Next EJSC.Chart.onDblClickPoint See Also Definition boolean onDblClickPoint( EJSC.Point point, EJSC.Series series, EJSC.Chart chart )...",""],
["./ejsc_chart_events_onshowcrosshairs.html","onShowCrosshairs","Top Previous Next EJSC.Chart.onShowCrosshairs See Also Definition void onShowCrosshairs( float x, float y, EJSC.Chart chart ) Description Called w...",""],
["./ejsc_chart_events_onshowhint.html","onShowHint","Top Previous Next EJSC.Chart.onShowHint See Also Definition string onShowHint( EJSC.Point point, EJSC.Series series, EJSC.Chart chart, DOMObject h...",""],
["./ejsc_chart_events_onshowmessage.html","onShowMessage","Top Previous Next EJSC.Chart.onShowMessage See Also Definition void onShowMessage( string message, string type ) Description Called when the statu...",""],
["./ejsc_chart_events_onxaxisneedsticks.html","onXAxisNeedsTicks","Top Previous Next EJSC.Chart.onXAxisNeedsTicks See Also Definition array onXAxisNeedsTicks( float x_min, float x_max, EJSC.Chart chart) Descriptio...",""],
["./ejsc_chart_events_onyaxisneedsticks.html","onYAxisNeedsTicks","Top Previous Next EJSC.Chart.onYAxisNeedsTicks Definition array onYAxisNeedsTicks( float y_min, float y_max, EJSC.Chart chart) Description This ev...",""],
["./ejsc_chart_methods_acquireseries.html","acquireSeries","Top Previous Next EJSC.Chart.acquireSeries See Also Definition void acquireSeries( EJSC.Series series, boolean redraw ) Description Moves a series...",""],
["./ejsc_chart_methods_addseries.html","addSeries","Top Previous Next EJSC.Chart.addSeries See Also Definition EJSC.Series addSeries( EJSC.Series series, boolean redraw ) Description Adds a new seri...",""],
["./ejsc_chart_methods_addxaxisbin.html","addXAxisBin","Top Previous Next EJSC.Chart.addXAxisBin See Also Definition void addXAxisBin( String label, boolean redraw ) Description Adds a new static label ...",""],
["./ejsc_chart_methods_addyaxisbin.html","addYAxisBin","Top Previous Next EJSC.Chart.addYAxisBin See Also Definition void addYAxisBin( String label, boolean redraw ) Description Adds a new static label ...",""],
["./ejsc_chart_methods_clearselectedpoint.html","clearSelectedPoint","Top Previous Next EJSC.Chart.clearSelectedPoint See Also Definition void clearSelectedPoint( ) Description Clears the current point selection and ...",""],
["./ejsc_chart_methods_convertpixeltopoint.html","convertPixelToPoint","Top Previous Next EJSC.Chart.convertPixelToPoint See Also Definition object convertPixelToPoint( integer left, integer top ) Result: { x: number, ...",""],
["./ejsc_chart_methods_convertpointtopixel.html","convertPointToPixel","Top Previous Next EJSC.Chart.convertPointToPixel See Also Definition object convertPointToPixel( number x, number y ) Result: { left: number, top:...",""],
["./ejsc_chart_methods_exportsvg.html","exportSVG","Top Previous Next EJSC.Chart.exportSVG See Also Definition string exportSVG( object Options ) Options Described (parameter {default value}) • incl...",""],
["./ejsc_chart_methods_exportsvglegend.html","exportSVGLegend","Top Previous Next EJSC.Chart.exportSVGLegend See Also Definition string exportSVGLegend( object Options ) Options Described (parameter {default va...",""],
["./ejsc_chart_methods_findclosestpointinseries.html","findClosestPointInSeries","Top Previous Next EJSC.Chart.findClosestPointInSeries See Also Definition EJSC.Point findClosestPointInSeries( float x, float y, EJSC.Series serie...",""],
["./ejsc_chart_methods_getminmaxyinxrange.html","getMinMaxYInXRange","Top Previous Next EJSC.Chart.getMinMaxYInXRange See Also Definition object getMinMaxYInXRange( float x_min, float x_max ) RETURNS: { y_min: float,...",""],
["./ejsc_chart_methods_getxextremes.html","getXExtremes","Top Previous Next EJSC.Chart.getXExtremes See Also Definition object getXExtremes( ) RETURNS: { x_min_extreme: float, x_max_extreme: float } Descr...",""],
["./ejsc_chart_methods_getyextremes.html","getYExtremes","Top Previous Next EJSC.Chart.getYExtremes See Also Definition object getYExtremes( ) RETURNS: { y_min_extreme: float, y_max_extreme: float } Descr...",""],
["./ejsc_chart_methods_getzoom.html","getZoom","Top Previous Next EJSC.Chart.getZoom See Also Definition object getZoom( ) RETURNS: { x_min: float, x_max: float, y_min: float, y_max: float } Des...",""],
["./ejsc_chart_methods_getzoomboxcoordinates.html","getZoomBoxCoordinates","Top Previous Next EJSC.Chart.getZoomBoxCoordinates See Also Definition object getZoomBoxCoordinates( ) RETURNS: { x_min: float, x_max: float, y_mi...",""],
["./ejsc_chart_methods_hidegrid.html","hideGrid","Top Previous Next EJSC.Chart.hideGrid See Also Definition void hideGrid( boolean redraw ) Description Hides the background grid and if redraw is o...",""],
["./ejsc_chart_methods_hidetitlebar.html","hideTitlebar","Top Previous Next EJSC.Chart.hideTitlebar See Also Definition void hideTitlebar( ) Description Hides the titlebar, resizes and chart area and redr...",""],
["./ejsc_chart_methods_hidexaxis.html","hideXAxis","Top Previous Next EJSC.Chart.hideXAxis See Also Definition void hideXAxis( ) Description Hides the X axis, resizes and chart area and redraws all ...",""],
["./ejsc_chart_methods_hideyaxis.html","hideYAxis","Top Previous Next EJSC.Chart.hideYAxis See Also Definition void hideYAxis( ) Description Hides the Y axis, resizes and chart area and redraws all ...",""],
["./ejsc_chart_methods_redraw.html","redraw","Top Previous Next EJSC.Chart.redraw See Also Definition void redraw( boolean reselectPoint ) Description Resizes chart elements (if necessary) and...",""],
["./ejsc_chart_methods_remove.html","remove","Top Previous Next EJSC.Chart.remove See Also Definition void remove( ) Description Removes the chart from the page, cleans up all attached events,...",""],
["./ejsc_chart_methods_removeseries.html","removeSeries","Top Previous Next EJSC.Chart.removeSeries See Also Definition void removeSeries( EJSC.Series series, boolean redraw ) Description Removes the spec...",""],
["./ejsc_chart_methods_removexaxisbin.html","removeXAxisBin","Top Previous Next EJSC.Chart.removeXAxisBin See Also Definition void removeXAxisBin( String label, boolean redraw ) Description Removes a bin (sta...",""],
["./ejsc_chart_methods_removeyaxisbin.html","removeYAxisBin","Top Previous Next EJSC.Chart.removeYAxisBin See Also Definition void removeYAxisBin( String label, boolean redraw ) Description Removes a bin (sta...",""],
["./ejsc_chart_methods_selectclosestpoint.html","selectClosestPoint","Top Previous Next EJSC.Chart.selectClosestPoint See Also Definition void selectClosestPoint( float x, float y ) Description Selects the point clos...",""],
["./ejsc_chart_methods_selectpoint.html","selectPoint","Top Previous Next EJSC.Chart.selectPoint See Also Definition void selectPoint( EJSC.Point point, boolean sticky ) Description Selects the point pr...",""],
["./ejsc_chart_methods_setcrosshairs.html","setCrosshairs","Top Previous Next EJSC.Chart.setCrosshairs See Also NOT FULLY IMPLEMENTED ",""],
["./ejsc_chart_methods_setlegendtitle.html","setLegendTitle","Top Previous Next EJSC.Chart.setLegendTitle See Also Definition void setLegendTitle( string title ) Description Updates the caption in the legend ...",""],
["./ejsc_chart_methods_settitle.html","setTitle","Top Previous Next EJSC.Chart.setTitle See Also Definition void setTitle( string title ) Description Updates the chart title shown in the title are...",""],
["./ejsc_chart_methods_setxaxiscapion.html","setXAxisCaption","Top Previous Next EJSC.Chart.setXAxisCaption See Also Definition void setXAxisCaption( string caption ) Description Updates the x-axis caption. Th...",""],
["./ejsc_chart_methods_setxextremes.html","setXExtremes","Top Previous Next EJSC.Chart.setXExtremes See Also Definition void setXExtremes( float x_min, float x_max ) Description Updates the manual extreme...",""],
["./ejsc_chart_methods_setyaxiscaption.html","setYAxisCaption","Top Previous Next EJSC.Chart.setYAxisCaption See Also Definition void setYAxisCaption( string caption ) Description Updates the y-axis caption. Th...",""],
["./ejsc_chart_methods_setyextremes.html","setYExtremes","Top Previous Next EJSC.Chart.setYExtremes See Also Definition void setYExtremes( float y_min, float y_max ) Description Updates the manual extreme...",""],
["./ejsc_chart_methods_setzoom.html","setZoom","Top Previous Next EJSC.Chart.setZoom See Also Definition: void setZoom( float x_min, float x_max, float y_min, float y_max ) Description Sets the ...",""],
["./ejsc_chart_methods_setzoomboxcoordinates.html","setZoomBoxCoordinates","Top Previous Next EJSC.Chart.setZoomBoxCoordinates See Also Definition voide setZoomBoxCoordinates( float x_min, float x_max, float y_min, float y...",""],
["./ejsc_chart_methods_showgrid.html","showGrid","Top Previous Next EJSC.Chart.showGrid See Also Definition void showGrid( boolean redraw ) Description Shows the background grid and if redraw is o...",""],
["./ejsc_chart_methods_showtitlebar.html","showTitlebar","Top Previous Next EJSC.Chart.showTitlebar See Also Definition void showTitlebar( ) Description Shows the titlebar, resizes and chart area and redr...",""],
["./ejsc_chart_methods_showxaxis.html","showXAxis","Top Previous Next EJSC.Chart.showXAxis See Also Definition void showXAxis( ) Description Shows the X axis, resizes and chart area and redraws all ...",""],
["./ejsc_chart_methods_showyaxis.html","showYAxis","Top Previous Next EJSC.Chart.showYAxis See Also Definition void showYAxis( ) Description Shows the Y axis, resizes and chart area and redraws all ...",""],
["./ejsc_chart_properies_allow_interactivity.html","allow_interactivity","Top Previous Next EJSC.Chart.allow_interactivity See Also Definition boolean allow_interactivity = true Description Defines if the chart can be in...",""],
["./ejsc_chart_properties_allow_hide_error.html","allow_hide_error","Top Previous Next EJSC.Chart.allow_hide_error See Also Definition boolean allow_hide_error = false Description Defines whether the chart can overw...",""],
["./ejsc_chart_properties_allow_mouse_wheel_zoom.html","allow_mouse_wheel_zoom","Top Previous Next EJSC.Chart.allow_mouse_wheel_zoom See Also Definition boolean allow_mouse_wheel_zoom = true Description Defines if the chart can...",""],
["./ejsc_chart_properties_allow_zoom.html","allow_zoom","Top Previous Next EJSC.Chart.auto_zoom See Also Definition boolean allow_zoom = true Description Defines if the chart can be zoomed. This is autom...",""],
["./ejsc_chart_properties_auto_find_point_by_x.html","auto_find_point_by_x","Top Previous Next EJSC.Chart.auto_find_point_by_x See Also Definition boolean auto_find_point_by_x = false Description Defines if the select point...",""],
["./ejsc_chart_properties_auto_zoom.html","auto_zoom","Top Previous Next EJSC.Chart.auto_zoom See Also Definition string auto_zoom = undefined Valid property values: &#39;x&#39; - NOT IMPLEMENTED &#39;y&#39; Descripti...",""],
["./ejsc_chart_properties_force_static_points.html","force_static_points","Top Previous Next EJSC.Chart.force_static_points See Also DEPRECIATED See force_static_points_x and force_static_points_y Definition boolean force...",""],
["./ejsc_chart_properties_force_static_points_x.html","force_static_points_x","Top Previous Next EJSC.Chart.force_static_points_x See Also Definition boolean force_static_points_x = false Description Defines if the chart shou...",""],
["./ejsc_chart_properties_force_static_points_y.html","force_static_points_y","Top Previous Next EJSC.Chart.force_static_points_y See Also Definition boolean force_static_points_y = false Description Defines if the chart shou...",""],
["./ejsc_chart_properties_legendtitle.html","legendTitle","Top Previous Next EJSC.Chart.legendTitle See Also Definition string legendTitle = \"Chart Legend\" Description Defines the caption displayed in the ...",""],
["./ejsc_chart_properties_proximity_snap.html","proximity_snap","Top Previous Next EJSC.Chart.proximity_snap See Also Definition integer proximity_snap = 5 Description Determines the maximum number of pixels awa...",""],
["./ejsc_chart_properties_show_crosshairs.html","show_crosshairs","Top Previous Next EJSC.Chart.show_crosshairs See Also Definition object show_crosshairs = { x: true, y: true } Description Defines if crosshairs s...",""],
["./ejsc_chart_properties_show_grid.html","show_grid","Top Previous Next EJSC.Chart.show_grid See Also Definition boolean show_grid = true Description Defines whether to draw the background grid on the...",""],
["./ejsc_chart_properties_show_hints.html","show_hints","Top Previous Next EJSC.Chart.show_hints See Also Definition boolean show_hints = true Description Defines whether hints should be selected when a ...",""],
["./ejsc_chart_properties_show_legend.html","show_legend","Top Previous Next EJSC.Chart.show_legend See Also Definition boolean show_legend = true Description Defines if the chart legend should be displaye...",""],
["./ejsc_chart_properties_show_messages.html","show_messages","Top Previous Next EJSC.Chart.show_messages See Also Definition boolean show_messages = true Description Defines if progress messages should be dis...",""],
["./ejsc_chart_properties_show_mouse_position.html","show_mouse_position","Top Previous Next EJSC.Chart.show_mouse_position See Also Definition boolean show_mouse_position = true Description Defines if the current mouse p...",""],
["./ejsc_chart_properties_show_titlebar.html","show_titlebar","Top Previous Next EJSC.Chart.show_titlebar See Also Definition boolean show_titlebar = true Description Defines if the titlebar (containing chart ...",""],
["./ejsc_chart_properties_show_x_axis.html","show_x_axis","Top Previous Next EJSC.Chart.show_x_axis See Also Definition boolean show_x_axis = true Description Defines if the X axis (containing x axis capti...",""],
["./ejsc_chart_properties_show_y_axis.html","show_y_axis","Top Previous Next EJSC.Chart.show_y_axis See Also Definition boolean show_y_axis = true Description Defines if the Y axis (containing y axis capti...",""],
["./ejsc_chart_properties_title.html","title","Top Previous Next EJSC.Chart.title See Also Definition string title = \"Emprise JavaScript Chart\" Description Defines the title of the chart. It is...",""],
["./ejsc_chart_properties_x_axis_caption.html","x_axis_caption","Top Previous Next EJSC.Chart.x_axis_caption See Also Definition string x_axis_caption = \"X Axis\" Description Defines the text to be displayed belo...",""],
["./ejsc_chart_properties_x_axis_classname.html","x_axis_className","Top Previous Next EJSC.Chart.x_axis_className See Also Definition string x_axis_className = \"\" Description Defines the CSS className to assign to ...",""],
["./ejsc_chart_properties_x_axis_extremes_ticks.html","x_axis_extremes_ticks","Top Previous Next EJSC.Chart.x_axis_extremes_ticks See Also Definition boolean x_axis_extremes_ticks = false Description Defines if the x_min and ...",""],
["./ejsc_chart_properties_x_axis_formatter.html","x_axis_formatter","Top Previous Next EJSC.Chart.x_axis_formatter See Also Definition EJSC.Formatter x_axis_formatter = EJSC.Formatter Description Defines the formatt...",""],
["./ejsc_chart_properties_x_axis_max_tick_interval.html","x_axis_max_tick_interval","Top Previous Next EJSC.Chart.x_axis_min_tick_interval See Also Definition integer x_axis_max_tick_interval = undefined Description Defines the max...",""],
["./ejsc_chart_properties_x_axis_minor_ticks.html","x_axis_minor_ticks","Top Previous Next EJSC.Chart.x_axis_minor_ticks See Also: Using Colors Definition object x_axis_minor_ticks = { show: false, color: \"rgb(0,0,0)\", ...",""],
["./ejsc_chart_properties_x_axis_min_tick_interval.html","x_axis_min_tick_interval","Top Previous Next EJSC.Chart.x_axis_min_tick_interval See Also Definition integer x_axis_min_tick_interval = undefined Description Defines the min...",""],
["./ejsc_chart_properties_x_axis_size.html","x_axis_size","Top Previous Next EJSC.Chart.x_axis_size See Also Definition integer x_axis_size = 20 Description Defines the height (in pixels) of the X-Axis tic...",""],
["./ejsc_chart_properties_x_axis_stagger_ticks.html","x_axis_stagger_ticks","Top Previous Next EJSC.Chart.x_axis_stagger_ticks See Also Definition boolean x_axis_stagger_ticks = true Description Determines whether the X-Axi...",""],
["./ejsc_chart_properties_x_axis_tick_classname.html","x_axis_tick_className","Top Previous Next EJSC.Chart.x_axis_tick_className See Also Definition string x_axis_tick_className = \"\" Description Defines the CSS className to ...",""],
["./ejsc_chart_properties_x_axis_tick_count.html","x_axis_tick_count","Top Previous Next EJSC.Chart.x_axis_tick_count See Also Definition integer x_axis_tick_count = undefined Description Defines the number of ticks t...",""],
["./ejsc_chart_properties_x_cursor_position_caption.html","x_cursor_position_caption","Top Previous Next EJSC.Chart.x_cursor_position_caption See Also Definition string x_cursor_position_text = \"X:\" Description Defines the text to di...",""],
["./ejsc_chart_properties_x_cursor_position_formatter.html","x_cursor_position_formatter","Top Previous Next EJSC.Chart.x_cursor_position_formatter See Also Definition EJSC.Formatter x_cursor_position_formatter = undefined Description De...",""],
["./ejsc_chart_properties_x_max.html","x_max","Top Previous Next EJSC.Chart.x_max See Also Definition float x_max = undefined Description Defines the current maximum X value of the chart. Examp...",""],
["./ejsc_chart_properties_x_min.html","x_min","Top Previous Next EJSC.Chart.x_min See Also Definition float x_min = undefined Description Defines the current minimum X value of the chart. Examp...",""],
["./ejsc_chart_properties_x_value_hint_caption.html","x_value_hint_caption","Top Previous Next EJSC.Chart.x_value_hint_caption See Also Definition string x_value_hint_caption = \"X Value:\" Description Defines the text to dis...",""],
["./ejsc_chart_properties_x_zero_plane.html","x_zero_plane","Top Previous Next EJSC.Chart.x_zero_plane See Also: Using Colors Definition object x_zero_plane = { color: \"rgb(0,0,0)\", show: false, thickness: 1...",""],
["./ejsc_chart_properties_y_axis_caption.html","y_axis_caption","Top Previous Next EJSC.Chart.y_axis_caption See Also Definition string y_axis_caption = \"Y Axis\" Description Defines the text to be displayed belo...",""],
["./ejsc_chart_properties_y_axis_classname.html","y_axis_className","Top Previous Next EJSC.Chart.y_axis_className See Also Definition string y_axis_className = \"\" Description Defines the CSS className to assign to ...",""],
["./ejsc_chart_properties_y_axis_extremes_ticks.html","y_axis_extremes_ticks","Top Previous Next EJSC.Chart.y_axis_extremes_ticks See Also Definition boolean y_axis_extremes_ticks = false Description Defines if the y_min and ...",""],
["./ejsc_chart_properties_y_axis_formatter.html","y_axis_formatter","Top Previous Next EJSC.Chart.y_axis_formatter See Also Definition EJSC.Formatter Y_axis_formatter = EJSC.Formatter Description Defines the formatt...",""],
["./ejsc_chart_properties_y_axis_max_tick_interval.html","y_axis_max_tick_interval","Top Previous Next EJSC.Chart.y_axis_max_tick_interval See Also Definition integer y_axis_max_tick_interval = undefined Description Defines the max...",""],
["./ejsc_chart_properties_y_axis_minor_ticks.html","y_axis_minor_ticks","Top Previous Next EJSC.Chart.y_axis_minor_ticks See Also: Using Colors Definition object y_axis_minor_ticks = { show: false, color: \"rgb(0,0,0)\", ...",""],
["./ejsc_chart_properties_y_axis_min_tick_interval.html","y_axis_min_tick_interval","Top Previous Next EJSC.Chart.y_axis_min_tick_interval See Also Definition integer y_axis_min_tick_interval = undefined Description Defines the min...",""],
["./ejsc_chart_properties_y_axis_size.html","y_axis_size","Top Previous Next EJSC.Chart.y_axis_size See Also Definition integer y_axis_size = 50 Description Defines the width (in pixels) of the Y-Axis tick...",""],
["./ejsc_chart_properties_y_axis_tick_classname.html","y_axis_tick_className","Top Previous Next EJSC.Chart.y_axis_tick_className See Also Definition string y_axis_tick_className = \"\" Description Defines the CSS className to ...",""],
["./ejsc_chart_properties_y_axis_tick_count.html","y_axis_tick_count","Top Previous Next EJSC.Chart.y_axis_tick_count See Also Definition integer y_axis_tick_count = undefined Description Defines the number of ticks t...",""],
["./ejsc_chart_properties_y_cursor_position_caption.html","y_cursor_position_caption","Top Previous Next EJSC.Chart.y_cursor_position_caption See Also Definition string y_cursor_position_text = \"Y:\" Description Defines the text to di...",""],
["./ejsc_chart_properties_y_cursor_position_formatter.html","y_cursor_position_formatter","Top Previous Next EJSC.Chart.y_cursor_position_formatter See Also Definition EJSC.Formatter y_cursor_position_formatter = undefined Description De...",""],
["./ejsc_chart_properties_y_max.html","y_max","Top Previous Next EJSC.Chart.y_max See Also Definition float y_max = undefined Description Defines the current maximum Y value of the chart. Examp...",""],
["./ejsc_chart_properties_y_min.html","y_min","Top Previous Next EJSC.Chart.y_min See Also Definition float y_min = undefined Description Defines the current minimum y value of the chart. Examp...",""],
["./ejsc_chart_properties_y_value_hint_caption.html","y_value_hint_caption","Top Previous Next EJSC.Chart.y_value_hint_caption See Also Definition string y_value_hint_caption = \"Y Value:\" Description Defines the text to dis...",""],
["./ejsc_chart_properties_y_zero_plane.html","y_zero_plane","Top Previous Next EJSC.Chart.y_zero_plane See Also: Using Colors Definition object y_zero_plane = { color: \"rgb(0,0,0)\", show: false, thickness: 1...",""],
["./ejsc_csvfiledatahandler.html","EJSC.CSVFileDataHandler","Top Previous Next EJSC.CSVFileDataHandler Hierarchy Properties Methods Events CSVFileDataHandler loads the requested csv file and extracts the dat...",""],
["./ejsc_csvfiledh_methods_geturl.html","getUrl","Top Previous Next EJSC.CSVFileDataHandler.getUrl See Also Definition string getUrl( ) Description Returns the url string currently stored in the C...",""],
["./ejsc_csvstringdatahandler.html","EJSC.CSVStringDataHandler","Top Previous Next EJSC.CSVStringDataHandler Hierarchy Methods Events CSVStringDataHandler converts the csv string provided into a format that the ...",""],
["./ejsc_csvstringdatahandler_methods_getcsv.html","getCSV","Top Previous Next EJSC.CSVStringDataHandler.getCSV See Also Definition array getCSV( ) Description Returns the csv string currently stored in the ...",""],
["./ejsc_csvstringdatahandler_methods_setcsv.html","setCSV","Top Previous Next EJSC.CSVStringDataHandler.setCSV See Also Definition void setCSV( string csv ) Description Updates the csv string stored in the ...",""],
["./ejsc_datahandler.html","EJSC.DataHandler","Top Previous Next EJSC.DataHandler Hierarchy Methods Events Base data handler class that defines properties, methods and events common to all data...",""],
["./ejsc_datahandler_events_ondataavailable.html","onDataAvailable (inherited)","Top Previous Next EJSC.DataHandler.onDataAvailable See Also Definition void onDataAvailable() Description Placeholder for storing an event to fire...",""],
["./ejsc_datahandler_methods_loaddata.html","loadData (inherited)","Top Previous Next EJSC.DataHandler.loadData See Also Definition void loadData( ) Description Placeholder method which should be used to clear (if ...",""],
["./ejsc_dateformatter.html","EJSC.DateFormatter","Top Previous Next EJSC.DateFormatter Hierarchy Properties Methods Use this formatter when you want to display date values in your charts. It can b...",""],
["./ejsc_dateformatter_properties_format_string.html","format_string","Top Previous Next EJSC.DateFormatter.format_string See Also Definition string format_string = \"\" Description The following format options are avai...",""],
["./ejsc_dateformatter_properties_timezoneoffset.html","timezoneOffset","Top Previous Next EJSC.DateFormatter.timezoneOffset See Also Definition integer timezoneOffset = undefined Description Used in conjunction with us...",""],
["./ejsc_dateformatter_properties_useutc.html","useUTC","Top Previous Next EJSC.DateFormatter.useUTC See Also Definition boolean useUTC = true Description Set this property to false to use the workstatio...",""],
["./ejsc_formatter.html","EJSC.Formatter","Top Previous Next EJSC.Formatter Hierarchy Properties Methods The top level Formatter class is used as a base for all label formatters. It defines...",""],
["./ejsc_formatter_methods_format.html","format (inherited)","Top Previous Next EJSC.Formatter.format See Also Definition string format( float value, integer precision ) Description Format is called when a va...",""],
["./ejsc_formatter_properties_format_string.html","format_string","Top Previous Next EJSC.Formatter.format_string See Also Definition string format_string = undefined Description Defines the format string. Classes...",""],
["./ejsc_functionseries.html","EJSC.FunctionSeries","Top Previous Next EJSC.FunctionSeries Hierarchy Properties Methods Events The FunctionSeries is rendered as a line based on the results of the fun...",""],
["./ejsc_functionseries_methods_setlinewidth.html","setLineWidth","Top Previous Next EJSC.FunctionSeries.setLineWidth See Also Definition void setLineWidth( integer width ) Description Updates the lineWidth proper...",""],
["./ejsc_functionseries_properties_linewidth.html","lineWidth","Top Previous Next EJSC.FunctionSeries.lineWidth See Also Definition integer lineWidth = 1 Description Defines the width of the line connecting ser...",""],
["./ejsc_gaugepoint.html","EJSC.GaugePoint","Top Previous Next EJSC.GaugePoint Hierarchy Properties GaugePoint is used to store an X point value (and optionally a label). This is used in the ...",""],
["./ejsc_gaugeseries.html","EJSC.GaugeSeries","Top Previous Next EJSC.GaugeSeries Hierarchy Properties Methods Events Base series class that holds all the generic information for each gauge ser...",""],
["./ejsc_inheritable.html","EJSC.Inheritable","Top Previous Next EJSC.Inheritable Hierarchy Base class from which all EJSC classes descend. There are no public properties, methods or events for...",""],
["./ejsc_lineseries.html","EJSC.LineSeries","Top Previous Next EJSC.LineSeries Hierarchy Properties Methods Events LineSeries is rendered by drawing a line from point to point. The constructo...",""],
["./ejsc_lineseries_events.html","Events","Top Previous Next Events Enter topic text here. ",""],
["./ejsc_lineseries_methods.html","Methods","Top Previous Next Methods Enter topic text here. ",""],
["./ejsc_lineseries_methods_setlinewidth.html","setLineWidth (inherited)","Top Previous Next EJSC.LineSeries.setLineWidth See Also Definition void setLineWidth( integer width ) Description Updates the lineWidth property a...",""],
["./ejsc_lineseries_properties_drawpoints.html","drawPoints (inherited)","Top Previous Next EJSC.LineSeries.drawPoints See Also Definition boolean drawPoints = false Description Determines whether the individual points i...",""],
["./ejsc_lineseries_properties_linewidth.html","lineWidth (inherited)","Top Previous Next EJSC.LineSeries.lineWidth See Also Definition integer lineWidth = 1 Description Defines the width of the line connecting series ...",""],
["./ejsc_lineseries_properties_pointbordercolor.html","pointBorderColor (inherited)","Top Previous Next EJSC.LineSeries.pointBorderColor See Also: Using Colors Definition string pointBorderColor = \"rgb(255,255,255)\" Description Defi...",""],
["./ejsc_lineseries_properties_pointbordersize.html","pointBorderSize (inherited)","Top Previous Next EJSC.LineSeries.pointBorderSize See Also Definition integer pointBorderSize = 0 Description Defines the size in pixels of the bo...",""],
["./ejsc_lineseries_properties_pointcolor.html","pointColor (inherited)","Top Previous Next EJSC.LineSeries.pointColor See Also: Using Colors Definition string pointColor = undefined Description Defines the color of the ...",""],
["./ejsc_lineseries_properties_pointsize.html","pointSize (inherited)","Top Previous Next EJSC.LineSeries.pointSize See Also Definition integer pointSize = undefined Description Defines the size of the point (circle) d...",""],
["./ejsc_numberformatter.html","EJSC.NumberFormatter","Top Previous Next EJSC.NumberFormatter Hierarchy Properties Methods Use this formatter when you want more control over the display of numeric valu...",""],
["./ejsc_numberformatter_properties_currency_align.html","currency_align","Top Previous Next EJSC.NumberFormatter.currency_align See Also Definition string currency_align = \"left\" Description Valid options are \"left\" and ...",""],
["./ejsc_numberformatter_properties_currency_position.html","currency_position","Top Previous Next EJSC.NumberFormatter.currency_position See Also Definition string currency_position = \"inner\" Description Valid options are ?inn...",""],
["./ejsc_numberformatter_properties_currency_symbol.html","currency_symbol","Top Previous Next EJSC.NumberFormatter.currency_symbol See Also Definition string currency_symbol = \"\" Description Specifies the symbol used to in...",""],
["./ejsc_numberformatter_properties_decimal_separator.html","decimal_seperator","Top Previous Next EJSC.NumberFormatter.decimal_separator See Also Definition string decimal_separator = \".\" Description Specifies the symbol used ...",""],
["./ejsc_numberformatter_properties_forced_decimals.html","forced_decimals","Top Previous Next EJSC.NumberFormatter.forced_decimals See Also Definition integer forced_decimals = 0 Description Specifies the number of decimal...",""],
["./ejsc_numberformatter_properties_negative_symbol.html","negative_symbol","Top Previous Next EJSC.NumberFormatter.negative_symbol See Also Definition string negative_symbol = \"-\" Description Specifies the formatting of ne...",""],
["./ejsc_numberformatter_properties_thousand_separator.html","thousand_seperator","Top Previous Next EJSC.NumberFormatter.thousand_separator See Also Definition string thousand_separator = \",\" Description Specifies the symbol use...",""],
["./ejsc_numberformatter_properties_variable_decimals.html","variable_decimals","Top Previous Next EJSC.NumberFormatter.variable_decimals See Also Definition string variable_decimals = undefined Description Specifies the number...",""],
["./ejsc_numberformatter_props_currency_align.html","currency_align","Top Previous Next EJSC.NumberFormatter.currency_align See Also Definition string currency_align = \"left\" Description Valid options are \"left\" and ...",""],
["./ejsc_numberformatter_props_currency_position.html","currency_position","Top Previous Next EJSC.NumberFormatter.currency_position See Also Definition string currency_position = \"inner\" Description Valid options are \"inn...",""],
["./ejsc_numberformatter_props_currency_symbol.html","currency_symbol","Top Previous Next EJSC.NumberFormatter.currency_symbol See Also Definition string currency_symbol = \"\" Description Specifies the symbol used to in...",""],
["./ejsc_numberformatter_props_decimal_separator.html","decimal_separator","Top Previous Next EJSC.NumberFormatter.decimal_separator See Also Definition string decimal_separator = \".\" Description Specifies the symbol used ...",""],
["./ejsc_numberformatter_props_forced_decimals.html","forced_decimals","Top Previous Next EJSC.NumberFormatter.forced_decimals See Also Definition integer forced_decimals = undefined Description Specifies the number of...",""],
["./ejsc_numberformatter_props_negative_symbol.html","negative_symbol","Top Previous Next EJSC.NumberFormatter.negative_symbol See Also Definition string negative_symbol = \"-\" Description Specifies the formatting of ne...",""],
["./ejsc_numberformatter_props_thousand_separator.html","thousand_separator","Top Previous Next EJSC.NumberFormatter.thousand_separator See Also Definition string thousand_separator = \",\" Description Specifies the symbol use...",""],
["./ejsc_numberformatter_props_variable_decimals.html","variable_decimals","Top Previous Next EJSC.NumberFormatter.variable_decimals See Also Definition string variable_decimals = undefined Description Specifies the number...",""],
["./ejsc_piepoint.html","EJSC.PiePoint","Top Previous Next EJSC.PiePoint Hierarchy Properties PiePoint is used to store an X point value (and optionally a label value). This is used in th...",""],
["./ejsc_pieseries.html","EJSC.PieSeries","Top Previous Next EJSC.PieSeries Hierarchy Properties Methods Events PieSeries is rendered by drawing slices to form an ellipse. Each slice repres...",""],
["./ejsc_pieseries_events_onpieceneedscolor.html","onPieceNeedsColor","Top Previous Next EJSC.PieSeries.onPieceNeedsColor See Also: Using Colors Definition boolean onPieceNeedsColor( EJSC.PiePoint point, EJSC.PieSerie...",""],
["./ejsc_pieseries_methods_findcenter.html","findCenter","Top Previous Next EJSC.PieSeries.findCenter See Also Definition object findCenter( EJSC.PiePoint point ) The object returned is formatted as: { x:...",""],
["./ejsc_pieseries_methods_findcenterofcurve.html","findCenterOfCurve","Top Previous Next EJSC.PieSeries.findCenterOfCurve See Also Definition object findCenterOfCurve( EJSC.PiePoint point ) The object returned is form...",""],
["./ejsc_pieseries_methods_getpoints.html","getPoints","Top Previous Next EJSC.PieSeries.getPoints See Also Definition array getPoints() Description This method returns an array of all EJSC.PiePoint obj...",""],
["./ejsc_pieseries_methods_gettotalvalue.html","getTotalValue","Top Previous Next EJSC.PieSeries.getTotalValue See Also Definition integer getTotalValue( ) Description Returns the current total value of the pie...",""],
["./ejsc_pieseries_methods_resettotalvalue.html","resetTotalValue","Top Previous Next EJSC.PieSeries.resetTotalValue See Also Definition void resetTotalValue( boolean redraw ) Description This method causes the ser...",""],
["./ejsc_pieseries_methods_setdefaultcolors.html","setDefaultColors","Top Previous Next EJSC.PieSeries.setDefaultColors See Also: Using Colors Definition void setDefaultColors( array colors, boolean reload ) Descript...",""],
["./ejsc_pieseries_methods_settotalvalue.html","setTotalValue","Top Previous Next EJSC.PieSeries.setTotalValue See Also Definition void setTotalValue( integer value, boolean redraw ) Description Sets the total ...",""],
["./ejsc_pieseries_properties_defaultcolors.html","defaultColors","Top Previous Next EJSC.PieSeries.defaultColors See Also: Using Colors Definition array defaultColors = EJSC.DefaultPieColors Description Defines t...",""],
["./ejsc_pieseries_properties_height.html","height","Top Previous Next EJSC.PieSeries.height See Also Definition string height = \"100%\" Description Defines the total height of the pie series. This ma...",""],
["./ejsc_pieseries_properties_position.html","position","Top Previous Next EJSC.PieSeries.position See Also Definition string position = \"center\" Description Defines the quadrant of the chart that the pi...",""],
["./ejsc_pieseries_properties_total_value.html","total_value","Top Previous Next EJSC.PieSeries.total_value See Also Definition integer total_value = undefined Description Defines the total value (sum) of all ...",""],
["./ejsc_pieseries_properties_treelegend.html","treeLegend","Top Previous Next EJSC.PieSeries.treeLegend See Also Definition boolean treeLegend = true Description Defines whether to display each pie piece in...",""],
["./ejsc_pieseries_properties_width.html","width","Top Previous Next EJSC.PieSeries.width See Also Definition string width = \"100%\" Description Defines the total width of the pie series. This may b...",""],
["./ejsc_point.html","EJSC.Point","Top Previous Next EJSC.Point Hierarchy Properties Base point class that holds all the generic information for each point that is being created. Al...",""],
["./ejsc_point_properties_label.html","label","Top Previous Next EJSC.Point.label See Also Definition string label = null Description Defines the point label. Currently this is only implemented...",""],
["./ejsc_point_properties_userdata.html","userdata","Top Previous Next EJSC.Point.userdata See Also Definition string userdata = null Description Stores a user-defined string related to the point. Th...",""],
["./ejsc_point_properties_x.html","x","Top Previous Next EJSC.Point.x See Also Definition float x = null Description Defines the point X value. This may be mapped to a text label automa...",""],
["./ejsc_point_properties_y.html","y","Top Previous Next EJSC.Point.y See Also Definition float y = null Description Defines point Y value. ",""],
["./ejsc_properties_defaultbarcolors.html","DefaultBarColors","Top Previous Next EJSC.DefaultBarColors See Also: Using Colors Definition array defaultBarColors = [ \"rgb(120,90,59)\", \"rgb(53,115,53)\", \"rgb(178,...",""],
["./ejsc_properties_defaultcolors.html","DefaultColors","Top Previous Next EJSC.DefaultColors See Also: Using Colors Definition array defaultColors = [ \"rgb(120,90,59)\", \"rgb(53,115,53)\", \"rgb(178,87,56)...",""],
["./ejsc_properties_defaultimagepath.html","DefaultImagePath","Top Previous Next EJSC.DefaultImagePath See Also Definition string DefaultImagePath = \"images/\" Description Relative path defining the path to all...",""],
["./ejsc_properties_defaultpiecolors.html","DefaultPieColors","Top Previous Next EJSC.DefaultPieColors See Also: Using Colors Definition array defaultPieColors = [ \"rgb(120,90,59)\", \"rgb(53,115,53)\", \"rgb(178,...",""],
["./ejsc_scatterseries.html","EJSC.ScatterSeries","Top Previous Next EJSC.ScatterSeries Hierarchy Properties Methods Events ScatterSeries is rendered by drawing a styled point for each x,y coordina...",""],
["./ejsc_scatterseries_methods_setpointstyle.html","setPointStyle","Top Previous Next EJSC.ScatterSeries.setPointStyle See Also Definition void setPointStyle( integer size, string style ) Description Updates the po...",""],
["./ejsc_scatterseries_properties_pointsize.html","pointSize","Top Previous Next EJSC.ScatterSeries.pointSize See Also Definition integer pointSize = 4 Description Defines the size of the point to be drawn. Po...",""],
["./ejsc_scatterseries_properties_pointstyle.html","pointStyle","Top Previous Next EJSC.ScatterSeries.pointStyle See Also Definition string pointStyle = \"triangle\" Styles: triangle box circle diamond Description...",""],
["./ejsc_series.html","EJSC.Series","Top Previous Next EJSC.Series Hierarchy Properties Methods Events Base series class that holds all the generic information for each series that is...",""],
["./ejsc_series_events_onafterdataavailable.html","onAfterDataAvailable (inherited)","Top Previous Next EJSC.Series.onAfterDataAvailable See Also Definition boolean onAfterDataAvailable( EJSC.Chart chart, EJSC.Series series ) Descri...",""],
["./ejsc_series_events_onaftervisibilitychange.html","onAfterVisibilityChange (inherited)","Top Previous Next EJSC.Series.onAfterVisibilityChange See Also Definition boolean onAfterVisibilityChange( EJSC.Series series, EJSC.Chart chart, b...",""],
["./ejsc_series_events_onbeforevisibilitychange.html","onBeforeVisibilityChange (inherited)","Top Previous Next EJSC.Series.onBeforeVisibilityChange See Also Definition boolean onBeforeVisibilityChange( EJSC.Series series, EJSC.Chart chart ...",""],
["./ejsc_series_methods_getdatahandler.html","getDataHandler (inherited)","Top Previous Next EJSC.Series.getDataHandler See Also Definition EJSC.DataHandler getDataHandler( ) Description Returns the EJSC.DataHandler desce...",""],
["./ejsc_series_methods_getvisibility.html","getVisibility (inherited)","Top Previous Next EJSC.Series.getVisibility See Also Definition boolean getVisibility( ) Description Returns a boolean indicating the series curre...",""],
["./ejsc_series_methods_hide.html","hide (inherited)","Top Previous Next EJSC.Series.hide See Also Definition void hide( ) Description Changes the series visible state, updates the legend (if applicabl...",""],
["./ejsc_series_methods_hidelegend.html","hideLegend (inherited)","Top Previous Next EJSC.Series.hideLegend See Also Definition void hideLegend( ) Description Changes the series legend item visible state. No effec...",""],
["./ejsc_series_methods_reload.html","reload (inherited)","Top Previous Next EJSC.Series.reload See Also Definition void reload( ) Description Triggers a series reload if the functionality is defined in a ...",""],
["./ejsc_series_methods_setcolor.html","setColor (inherited)","Top Previous Next EJSC.Series.setColor See Also: Using Colors Definition void setColor( string color ) Description Changes the series color and ca...",""],
["./ejsc_series_methods_setcoloredlegend.html","setColoredLegend (inherited)","Top Previous Next EJSC.Series.setColoredLegend See Also Definition void setColoredLegend( boolean coloredLegend ) Description Sets the EJSC.Series...",""],
["./ejsc_series_methods_setdatahandler.html","setDataHandler (inherited)","Top Previous Next EJSC.Series.setDataHandler See Also Definition void setDataHandler( EJSC.DataHandler dataHandler, boolean reload ) Description U...",""],
["./ejsc_series_methods_setlineopacity.html","setLineOpacity","Top Previous Next EJSC.Series.setLineOpacity See Also Definition void setLineOpacity( integer opacity ) Description Sets the EJSC.Series.lineOpaci...",""],
["./ejsc_series_methods_setlinewidth.html","setLineWidth (inherited)","Top Previous Next EJSC.Series.setLineWidth See Also Definition void setLineWidth( integer width ) Description Updates the lineWidth property and r...",""],
["./ejsc_series_methods_setopacity.html","setOpacity (inherited)","Top Previous Next EJSC.Series.setOpacity See Also Definition void setOpacity( integer opacity ) Description Sets the EJSC.Series.opacity property ...",""],
["./ejsc_series_methods_settitle.html","setTitle (inherited)","Top Previous Next setTitle Definition void setTitle( string title ) Description Changes the series title and update the legend caption (if applica...",""],
["./ejsc_series_methods_show.html","show (inherited)","Top Previous Next EJSC.Series.show See Also Definition void show( ) Description Changes the series visible state, updates the legend (if applicabl...",""],
["./ejsc_series_methods_showlegend.html","showLegend (inherited)","Top Previous Next EJSC.Series.showLegend See Also Definition void showLegend( ) Description Changes the series legend item visible state. No effec...",""],
["./ejsc_series_properties_autosort.html","autosort (inherited)","Top Previous Next EJSC.Series.autosort See Also Definition boolean autosort = true Description Defines whether the series applies the appropriate ...",""],
["./ejsc_series_properties_color.html","color (inherited)","Top Previous Next EJSC.Series.color See Also: Using Colors Definition string color = undefined Description Defines the series color. If left undef...",""],
["./ejsc_series_properties_coloredlegend.html","coloredLegend (inherited)","Top Previous Next EJSC.Series.coloredLegend See Also Definition boolean coloredLegend = true Description Determines whether the legend text inheri...",""],
["./ejsc_series_properties_delayload.html","delayLoad (inherited)","Top Previous Next EJSC.Series.delayLoad See Also EXPERIMENTAL Definition boolean delayLoad = true Description This property allows a series to for...",""],
["./ejsc_series_properties_legendisvisible.html","legendIsVisible (inherited)","Top Previous Next EJSC.Series.legendIsVisible See Also Definition boolean legendIsVisible = true Description Determines whether the legend item as...",""],
["./ejsc_series_properties_lineopacity.html","lineOpacity (inherited)","Top Previous Next EJSC.Series.lineOpacity See Also Definition integer lineOpacity = 100 Description Determines the line opacity (if applicable) of...",""],
["./ejsc_series_properties_linewidth.html","lineWidth (inherited)","Top Previous Next EJSC.Series.lineWidth See Also Definition integer lineWidth = 1 Description Defines the width of the line connecting series poin...",""],
["./ejsc_series_properties_opacity.html","opacity (inherited)","Top Previous Next EJSC.Series.opacity See Also Definition integer opacity = 50 Description Determines the fill opacity (if applicable) of the seri...",""],
["./ejsc_series_properties_title.html","title (inherited)","Top Previous Next EJSC.Series.title See Also Definition string title = \"Series &#60;index&#62;\" Description Defines the series title used in hints and leg...",""],
["./ejsc_series_properties_visible.html","visible (inherited)","Top Previous Next EJSC.Series.visible See Also Definition boolean visible = true Description Defines whether the series is visible and can draw on...",""],
["./ejsc_series_properties_x_axis_formatter.html","x_axis_formatter (inherited)","Top Previous Next EJSC.Series.x_axis_formatter See Also Definition string x_axis_formatter = undefined Description Defines the formatter that will...",""],
["./ejsc_series_properties_y_axis_formatter.html","y_axis_formatter (inherited)","Top Previous Next EJSC.Series.y_axis_formatter See Also Definition string y_axis_formatter = undefined Description Defines the formatter that will...",""],
["./ejsc_trendseries.html","EJSC.TrendSeries","Top Previous Next EJSC.TrendSeries Hierarchy Properties Methods Events The TrendSeries is rendered as a line based on the results of a function ap...",""],
["./ejsc_xmldatahandler.html","EJSC.XMLDataHandler","Top Previous Next EJSC.XMLDataHandler Hierarchy Properties Methods Events XMLDataHandler loads the requested XML file, determines the format (Full...",""],
["./ejsc_xmldatahandler_methods_geturl.html","getUrl","Top Previous Next EJSC.XMLDataHandler.getUrl See Also Definition string getUrl( ) Description Returns the url string currently stored in the XMLDa...",""],
["./ejsc_xmldatahandler_methods_seturl.html","setUrl","Top Previous Next EJSC.XMLDataHandler.setUrl See Also Definition void setUrl( string url ) Description Updates the url string stored in the XMLDat...",""],
["./ejsc_xmlstringdatahandler.html","EJSC.XMLStringDataHandler","Top Previous Next EJSC.XMLStringDataHandler Hierarchy Methods Events XMLStringDataHandler processes the provided xml-formatted string, determines ...",""],
["./ejsc_xmlstringdatahandler_methods_getxml.html","getXML","Top Previous Next EJSC.XMLStringDataHandler.getXML See Also Definition string getXML( ) Description Returns the xml string currently stored in the...",""],
["./ejsc_xmlstringdatahandler_methods_setxml.html","setXML","Top Previous Next EJSC.XMLStringDataHandler.setXML See Also Definition void setXML( string xml ) Description Updates the xml string stored in the ...",""],
["./ejsc_xypoint.html","EJSC.XYPoint","Top Previous Next EJSC.XYPoint Hierarchy Properties XYPoint is used to store a X,Y point value. This is used in series such as EJSC.LineSeries , E...",""],
["./esjc_csvfiledh_methods_seturl.html","setUrl","Top Previous Next EJSC.CSVFileDataHandler.setUrl See Also Definition void setUrl( string url ) Description Updates the url string stored in the CS...",""],
["./examplescodesnippets.html","Examples &#38; Code Snippets","Top Previous Next Examples &#38; Code Snippets Enter topic text here. ",""],
["./exporting_to_svg.html","Exporting To SVG","Top Previous Next Exporting To SVG Including SVG Export Functionality To add the SVG Export functionality to your current implementation, simply i...",""],
["./getting_support.html","Getting Support","Top Previous Getting Support There are a wide variety of technical support options available for Emprise software products. For users who have pur...",""],
["./gsg_anatomy_chartbody.html","Chart Body","Top Previous Next Chart Body ",""],
["./gsg_anatomy_hint.html","Hint","Top Previous Next Hint ",""],
["./gsg_anatomy_legend.html","Legend","Top Previous Next Legend ",""],
["./gsg_anatomy_titlebar.html","Titlebar","Top Previous Next Titlebar ",""],
["./gsg_anatomy_xaxis.html","X Axis","Top Previous Next X Axis ",""],
["./gsg_anatomy_yaxis.html","Y Axis","Top Previous Next Y Axis ",""],
["./gsg_creatingyourfirstchart.html","Creating Your First Chart","Top Previous Next Creating Your First Chart Now that you have created and tested your first demonstration chart on your web server it is time to c...",""],
["./gsg_customizingyourchart.html","Customizing Your Chart","Top Previous Next Customizing Your Chart With Emprise JavaScript Charts, the customization options of your chart are endless. This includes visual...",""],
["./gsg_implementationinstructions.html","Implementation Instructions","Top Previous Next Implementation Instructions Ease of implementation was an important factor considered in the development of EJSChart. The proces...",""],
["./gsg_overview.html","Overview","Top Next Overview Welcome to Emprise JavaScript Charts. Constructed entirely in JavaScript the days of annoying plugin downloads and browser secur...",""],
["./text_replacement_options.html","Text Replacement Options","Top Previous Next Text Replacement Options String Replaced With [chart_title] The title of the chart [series_title] The title of the series the se...",""],
["./using_colors.html","Using Colors","Top Previous Next Using Colors Using Colors Colors may be specified in any of the following formats: RGB: \"rgb( &#60;red&#62;, &#60;green&#62;, &#60;blue&#62; )\" example:...",""],
["./welcometopic.html","Getting Started","Top Next Getting Started Anatomy of a Chart ",""]];
